# Generated by Django 6.1.1 on 2026-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_pin',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
